// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA6JJmKq7m7NYtsYTmxCl8VFMAAO9DyjXY',
    appId: '1:1014440446082:web:1fa759318190cdfdf14c9b',
    messagingSenderId: '1014440446082',
    projectId: 'dicoding-ditonton-f435d',
    authDomain: 'dicoding-ditonton-f435d.firebaseapp.com',
    storageBucket: 'dicoding-ditonton-f435d.appspot.com',
    measurementId: 'G-L7Y8SRXJZR',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBZmJyAekVLeWVFYIZRAE0Qb2yGx9iZWQU',
    appId: '1:1014440446082:android:ea95c7e3e12a5fc1f14c9b',
    messagingSenderId: '1014440446082',
    projectId: 'dicoding-ditonton-f435d',
    storageBucket: 'dicoding-ditonton-f435d.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCze3d4hVWa0HHgNlZHwn-2NrrJ07l9mqg',
    appId: '1:1014440446082:ios:9eb85347e0b99ea3f14c9b',
    messagingSenderId: '1014440446082',
    projectId: 'dicoding-ditonton-f435d',
    storageBucket: 'dicoding-ditonton-f435d.appspot.com',
    iosClientId: '1014440446082-sj04vg9pfviheek407er9iakav6ecii8.apps.googleusercontent.com',
    iosBundleId: 'com.dicoding.ditonton',
  );
}
